version: '3'
services:

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/usr/src/app
    ports:
      - 3040:3000
    depends_on:
      - mysql
    links:
      - mysql


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ~/Downloads:/mnt/downloads
